In [5]:
import torch
import numpy as np

In [2]:
import torch
from torch import nn
torch.tensor([1.0, 2.0]).cuda()

tensor([1., 2.], device='cuda:0')

In [3]:
import torch
from torch import nn
m = nn.Conv1d(16,33,3, stride=2)
m = m.to('cuda')
input = torch.randn(20,16,50)
input = input.to('cuda')
output = m(input)

In [4]:
# output

In [6]:
var = torch.tensor([1 , 3, 4])

In [8]:
n = var.clone().data.cpu().numpy()
n

array([1, 3, 4])

In [10]:
n[2] = 0
n

array([1, 3, 0])

In [11]:
var

tensor([1, 3, 4])